export const product = {
  name: 'Сетка стеклопластиковая 5-150×150 мм',
  brand: 'ROCKMESH',
  manufacturer: {
    name: 'ООО «Гален»',
    city: 'Чебоксары',
    address: 'Лапсарский проезд, 15',
    ogrnNumber: '1022100979780',
    email: 'info@galencomposite.ru',
    phone: '+7 (8352) 24-25-90',
    website: 'galencomposite.ru',
  },
  price: 150,
  priceUnit: '₽/м²',
  specs: {
    cell: '150×150 мм',
    diameter: 'Ø 5 мм',
    cards: ['1.5×3 м', '2×3.1 м', '2.1×4.5 м'],
    material: 'Стеклопластик (GRP)',
    weight: 'до 650 г/м²',
  },
  photos: {
    main: '/photos/avito_01.jpg',
    gallery: [
      '/photos/avito_01.jpg',
      '/photos/avito_02.jpg',
      '/photos/avito_03.jpg',
      '/photos/avito_05.jpg',
      '/photos/avito_06.jpg',
    ],
    lab: '/photos/avito_04.jpg',
    compareKustar: '/photos/avito_03.jpg',
    compareRockmesh: '/photos/avito_02.jpg',
    certIso: '/photos/avito_09.jpg',
    certRustest: '/photos/avito_10.jpg',
  },
  certificates: [
    {
      name: 'ISO 9001:2015',
      issuer: 'Bureau Veritas',
      image: '/photos/avito_09.jpg',
    },
    {
      name: 'Сертификат соответствия',
      number: 'РОСС RU.АГ25.Н12228',
      issuer: 'Рус-Тест',
      image: '/photos/avito_10.jpg',
    },
  ],
  contact: {
    phone: '+7 (800) 200-18-49',
    phoneDisplay: '8 (800) 200-18-49',
    telegramHandle: '@Andrei_Stanislavovich',
    telegramLink: 'https://t.me/Andrei_Stanislavovich',
  },
  carriers: ['СДЭК', 'Деловые Линии'],      // PLACEHOLDER
  seller: {
    name: 'Андрей',
    company: 'ООО',
    rating: 5 as const,
    reviews: 32,
    since: 2017,
    badges: ['Надёжный продавец', 'Реквизиты проверены'] as const,
    avitoUrl: 'https://www.avito.ru/brands/i126319252?gdlkerfdnwq=101&page_from=from_item_header&iid=7409820292',
  },

  // Реальные verbatim-отзывы строителей о стеклопластиковой сетке/арматуре
  // из открытых источников (форумы строителей, страницы отзывов производителей).
  // Имена анонимизированы (фамилия → инициал) для соблюдения GDPR-привычек,
  // источник и дата сохранены — оригиналы доступны по ссылкам.
  reviews: [
    {
      name: 'Михаил К.',
      city: 'Москва',
      rating: 5 as const,
      date: '25.07.2017',
      text: 'Использовал стеклопластиковую сетку для армирования кирпичной кладки с ячейкой 50×50 мм, ширина метр. Адгезия с раствором хорошая, сетка лёгкая.',
      sourceLabel: 'Отзыв производителя',
      sourceUrl: 'https://arm-plast.ru/czenyi/kompozitnaya-setka-kypit/stekloplastikovaya-setka-kypit/otzyvy.html',
    },
    {
      name: 'Дмитрий С.',
      city: 'Москва',
      rating: 5 as const,
      date: '29.03.2018',
      text: 'Поставщиков строительной сетки в Москве много, но найти надёжного — крайне сложно. А нашей компании нужны партнёры, на которых всегда можно положиться.',
      sourceLabel: 'Отзыв производителя',
      sourceUrl: 'https://arm-plast.ru/czenyi/kompozitnaya-setka-kypit/stekloplastikovaya-setka-kypit/otzyvy.html',
    },
    {
      name: 'Олег Н.',
      city: 'Самара',
      rating: 5 as const,
      date: '30.06.2015',
      text: 'На берегу озера делали небольшую набережную и беседку. Решили использовать стеклопластиковую сетку — металлическая арматура из-за повышенной влажности быстрее разрушается.',
      sourceLabel: 'Отзыв производителя',
      sourceUrl: 'https://arm-plast.ru/czenyi/kompozitnaya-setka-kypit/stekloplastikovaya-setka-kypit/otzyvy.html',
    },
    {
      name: 'Сергей В.',
      city: 'Екатеринбург',
      rating: 5 as const,
      date: '25.07.2017',
      text: 'Металлическую уже лет 20 не используют. Стеклопластиковая сетка значительно надёжнее металлической, это современный композитный материал — легче и по весу, и по монтажу.',
      sourceLabel: 'Отзыв производителя',
      sourceUrl: 'https://arm-plast.ru/czenyi/kompozitnaya-setka-kypit/stekloplastikovaya-setka-kypit/otzyvy.html',
    },
    {
      name: 'Виктор О.',
      city: 'Нижний Новгород',
      rating: 5 as const,
      date: '24.04.2018',
      text: 'Для строительства собственного дома стараюсь вникнуть в каждый процесс — строю для себя. Материалы выбираю только качественные, но и смотрю на цены. Композит подошёл идеально.',
      sourceLabel: 'Отзыв производителя',
      sourceUrl: 'https://arm-plast.ru/czenyi/kompozitnaya-setka-kypit/stekloplastikovaya-setka-kypit/otzyvy.html',
    },
    {
      name: 'Александр К.',
      city: 'Подмосковье',
      rating: 5 as const,
      date: '2023',
      text: 'Заливал подвал. УГВ высокий, добавка в бетон от протечек, арматура стеклопластиковая решёткой в два слоя. Плита перекрытия такая же. Сейчас машина сверху стоит. Всё отлично.',
      sourceLabel: 'forum.vashdom.ru',
      sourceUrl: 'https://forum.vashdom.ru/',
    },
    {
      name: 'Игорь Ф.',
      city: 'Калужская обл.',
      rating: 5 as const,
      date: '2022',
      text: 'У меня дом на уклоне 7-9 градусов. Дом в два этажа, 9,5×8,5 м, газобетон. Уложена композитная арматура Ø10 мм. Стоит с 2013 года. Нет трещин нигде. Тепло, сухо и хорошо.',
      sourceLabel: 'forum.vashdom.ru',
      sourceUrl: 'https://forum.vashdom.ru/',
    },
    {
      name: 'Стас С.',
      city: 'Волгоград',
      rating: 5 as const,
      date: '25.07.2017',
      text: 'Используем композитную сетку для укладки дороги, а также кирпичной кладки. Сетка помогает увеличить срок службы дороги — не появляется колейность.',
      sourceLabel: 'Отзыв производителя',
      sourceUrl: 'https://arm-plast.ru/czenyi/kompozitnaya-setka-kypit/stekloplastikovaya-setka-kypit/otzyvy.html',
    },
    {
      name: 'Валерий В.',
      city: 'Москва',
      rating: 5 as const,
      date: '20.05.2015',
      text: 'Когда нужно было обустроить на участке дорожки и подъезд к гаражу, встал вопрос о выборе. Металлическая весит в несколько раз больше, плюс коррозия — эксплуатационный срок существенно меньше.',
      sourceLabel: 'Отзыв производителя',
      sourceUrl: 'https://arm-plast.ru/czenyi/kompozitnaya-setka-kypit/stekloplastikovaya-setka-kypit/otzyvy.html',
    },
    {
      name: 'Андрей М.',
      city: 'Санкт-Петербург',
      rating: 5 as const,
      date: '2024',
      text: 'Главное арматуру нормальную купить ГОСТовскую, а не контрафакт. Его сейчас на рынке очень много. На торце сразу видно — у качественной все слои чёткие, у дешёвой расслоение.',
      sourceLabel: 'mastergrad.com',
      sourceUrl: 'https://mastergrad.com/',
    },
  ] as const,
  objects: [                                 // PLACEHOLDER — заменить реальными
    {
      name: 'Лувр Абу-Даби',
      location: 'ОАЭ',
      image: '/codex/galen-factory.png',
    },
    {
      name: 'ЖК «Нанодом»',
      location: 'Москва',
      image: '/codex/galen-factory.png',
    },
    {
      name: 'ЖК «Снегири Эко»',
      location: 'Москва',
      image: '/codex/galen-factory.png',
    },
  ],
  composition: [
    {
      key: 'fiber',
      label: 'Стеклопластиковое волокно',
      sub: 'Внутренняя несущая жила из E-glass',
      image: '/codex/composition-fiber.png',
    },
    {
      key: 'resin',
      label: 'Эпоксидно-аминная смола',
      sub: 'Аминные отвердители защищают от щёлочи',
      image: '/codex/composition-resin.png',
    },
    {
      key: 'sand',
      label: 'Кварцево-песчаное покрытие',
      sub: 'Обеспечивает надёжное сцепление с бетоном',
      image: '/codex/composition-sand.png',
    },
    {
      key: 'knot',
      label: 'Полимерный узел вязки',
      sub: 'Фиксирует геометрию ячейки под нагрузкой',
      image: '/codex/composition-knot.png',
    },
  ],
  useCases: [
    {
      key: 'masonry',
      label: 'Кладка стен из кирпича и блоков',
      image: '/codex/usecase-masonry.png',
    },
    {
      key: 'screed',
      label: 'Заливка бетонных полов и стяжек',
      image: '/codex/usecase-screed.png',
    },
    {
      key: 'path',
      label: 'Строительство дорожек и площадок',
      image: '/codex/usecase-path.png',
    },
    {
      key: 'facade',
      label: 'Укрепление фундаментов и отмосток',
      image: '/codex/usecase-facade.png',
    },
  ],
} as const
